- gradle.properties
- src/main/java/com/jfrog/ide/common/configuration/XrayServerConfig.java
- src/main/java/com/jfrog/ide/common/scan/ScanManagerBase.java
Add support for proxy in check connection button
> Add host url to getProxyConfig

- Jenkinsfile
> DEVF-874 - Changed credentials implementation

- build.gradle
- src/main/java/com/jfrog/ide/common/configuration/XrayServerConfig.java
- src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
- src/main/java/com/jfrog/ide/common/scan/ScanManagerBase.java
- src/test/java/com/jfrog/ide/common/npm/NpmTreeBuilderTest.java
Depends on: https://github.com/jfrog/xray-client-java/pull/9
* Use the new Xray client builder.
* Add connection retries and connection timeout.
> Migrate HTTP client to PreemptiveHttpClient

- build.gradle
- src/main/java/com/jfrog/ide/common/configuration/ServerConfig.java
- src/main/java/com/jfrog/ide/common/scan/ScanManagerBase.java
- src/main/java/com/jfrog/ide/common/utils/Utils.java
* Add support for providing Artifactory and JFrog platform URLs
* Upgrade build-info dependencies
Precondition to: https://github.com/jfrog/jfrog-idea-plugin/pull/103
> Add support for providing Artifactory and JFrog platform URLs

- src/main/java/com/jfrog/ide/common/utils/PackageFileFinder.java
When a directory is excluded, log the exclusion in the event log:
```
Excluding directory 'dir-path' from Xray scanning due to the defined Excluded Paths pattern
```
Would help in cases of:
https://github.com/jfrog/jfrog-idea-plugin/issues/108
> Log the excluded paths

- src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
Run `go mod graph` in a new temp directory contains only a copy of the `go.mod` file.
This behavior is necessary to bypass checksum mismatches issues in the original `go.sum`.
> Build Go dependency trees in temp directories

- src/main/java/com/jfrog/ide/common/ci/BuildArtifactsDownloader.java
- src/main/java/com/jfrog/ide/common/ci/CiManagerBase.java
- src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
- src/main/java/com/jfrog/ide/common/gradle/GradleTreeBuilder.java
- src/main/java/com/jfrog/ide/common/log/Utils.java
- src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
- src/main/java/com/jfrog/ide/common/persistency/BuildsScanCache.java
- src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java
- src/main/java/com/jfrog/ide/common/scan/ScanManagerBase.java
- src/test/java/com/jfrog/ide/common/npm/NpmTreeBuilderTest.java
To get a better user experience, balloons should be shown only when that user initiates the scan.
Precondition for: https://github.com/jfrog/jfrog-idea-plugin/pull/136
> Popup balloons only on interactive scans

- build.gradle
> Remove OJO from build.gradle

- src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
- src/main/java/com/jfrog/ide/common/gradle/GradleTreeBuilder.java
- src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
- src/main/java/com/jfrog/ide/common/scan/ScanLogic.java
> BugFix: Cache for Multi Projects/Modules

- src/main/java/com/jfrog/ide/common/utils/PackageFileFinder.java
> Improve excluded paths log message

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
- src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
- src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
-----
Added a new JFrog CLI driver to get local configured JFrog platform servers.
> Add new JFrog CLI driver

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
- src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
- src/main/java/com/jfrog/ide/common/configuration/ServerConfig.java
- src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
- src/main/java/com/jfrog/ide/common/utils/XrayConnectionUtils.java
- src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
> Add access token support

- src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
- src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java
- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
- src/main/java/com/jfrog/ide/common/utils/Utils.java
- src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java
- src/test/java/com/jfrog/ide/common/scan/ScanLogicTest.java
- src/test/resources/scanResponses/graphScanViolations.json
- src/test/resources/scanResponses/graphScanVulnerabilities.json
- src/test/resources/scanResponses/summaryComponent.json
-----
Depends on:
* https://github.com/jfrog/xray-client-java/pull/27
* https://github.com/jfrog/build-info/pull/589
Fix the following issues:
* Issues with the same component and summary are deduped
* Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/180
* Before:
* After: 
* Empty meaningless issues.
* Before:
* After:
* All licenses marked as violated.
* Before: 
* After:
* Licenses contain no link.
* Before:
* After:
After these changed, I added tests for `ComponentSummaryScanLogic` and `GraphScanLogic`.
> Populate missing fields of violations and vulnerabilities

- src/main/java/com/jfrog/ide/common/log/ProgressIndicator.java
- src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
- src/test/java/com/jfrog/ide/common/scan/ScanLogicTest.java
-----
Depends on https://github.com/jfrog/xray-client-java/pull/29
Add progress indicator in GraphScanLogic.
See example in https://github.com/jfrog/jfrog-idea-plugin/pull/188.
> Improve progress indicator

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
- src/main/java/com/jfrog/ide/common/configuration/ServerConfig.java
- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
- src/test/java/com/jfrog/ide/common/scan/ScanLogicTest.java
-----
Depends on https://github.com/jfrog/xray-client-java/pull/30
Dependency for https://github.com/jfrog/jfrog-idea-plugin/pull/189
> Support Xray watches

- src/main/java/com/jfrog/ide/common/ci/BuildDependencyTree.java
- src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
-----
Depends on https://github.com/jfrog/build-info/pull/627
Fixes https://github.com/jfrog/jfrog-idea-plugin/issues/203
Make sure there isn't a loop in the CI dependency tree before adding a new node.
> Bugfix - Stackoverflow in CI tree when there is a loop

- src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
- src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
-----
Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/208
Depends on https://github.com/jfrog/build-info/pull/634
> Allow missing modules in Go

- src/test/java/com/jfrog/ide/common/npm/NpmTreeBuilderTest.java
> Fix NpmTreeBuilderTest

- src/main/java/com/jfrog/ide/common/ci/BuildGeneralInfo.java
- src/main/java/com/jfrog/ide/common/ci/CiManagerBase.java
- src/main/java/com/jfrog/ide/common/ci/Utils.java
- src/main/java/com/jfrog/ide/common/ci/XrayBuildDetailsDownloader.java
- src/test/java/com/jfrog/ide/common/ci/CiManagerBaseTest.java
> Bugfix - handle build number with colon (":")

- build.gradle
- src/main/java/com/jfrog/ide/common/gradle/GradleDriver.java
-----
Depends on https://github.com/jfrog/gradle-dep-tree/pull/5
May resolve https://github.com/jfrog/jfrog-idea-plugin/issues/225
> Gradle - write the output paths to an input file

- .github/workflows/frogbot-scan-pull-request.yml
> Add Frogbot to this repository

- src/main/java/com/jfrog/ide/common/ci/XrayBuildDetailsDownloader.java
> CI - Missing Xray scan results

- build.gradle
> Update build-info version to 2.37.4

- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
> Remove duplications of components in Xray scan

- .github/workflows/test.yml
- src/test/resources/gradle/kotlin/build.gradle.kts
- src/test/resources/gradle/unresolvedKotlin/build.gradle.kts
> Fix GradleTreeBuilderTest

- src/main/java/com/jfrog/ide/common/tree/BaseTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/ComparableSeverityTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/DependencyNode.java
- src/main/java/com/jfrog/ide/common/tree/DescriptorFileTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/FileTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/IssueNode.java
- src/main/java/com/jfrog/ide/common/tree/Severity.java
- src/main/java/com/jfrog/ide/common/tree/VulnerabilityOrViolationNode.java
> Add new No-Applicable severity type

- src/main/java/com/jfrog/ide/common/gradle/GradleTreeBuilder.java
- src/test/java/com/jfrog/ide/common/gradle/GradleTreeBuilderTest.java
-----
Same as https://github.com/jfrog/jfrog-idea-plugin/pull/257
> Remove "unresolved" from Gradle nodes

- src/main/java/com/jfrog/ide/common/tree/ApplicableIssueNode.java
-----
Added ScannerSearchTarget field for the new contextual analysis view.
> Added scannerSearchTarget in ApplicableIssueNode

- src/main/java/com/jfrog/ide/common/tree/DependencyNode.java
- src/main/java/com/jfrog/ide/common/tree/DescriptorFileTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/FileTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/GeneralInfo.java
- src/main/java/com/jfrog/ide/common/tree/ImpactTreeNode.java
- src/main/java/com/jfrog/ide/common/utils/Utils.java
> Changes to support IDEA code inspections

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Upgrade to gradle 7.6

- src/main/java/com/jfrog/ide/common/tree/ApplicableIssueNode.java
- src/main/java/com/jfrog/ide/common/tree/ComparableSeverityTreeNode.java
- src/main/java/com/jfrog/ide/common/tree/IssueNode.java
- src/main/java/com/jfrog/ide/common/tree/Severity.java
-----
Support better visualization for not applicable security issues.
> Add new "not applicable severity" types

- build.gradle
- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
- src/main/java/com/jfrog/ide/common/tree/IssueNode.java
> Add support for issue's ignore rule creation

- src/main/java/com/jfrog/ide/common/nodes/subentities/Severity.java
-----
Not applicable issues should have lower severity than any applicable (or unknown) issue.
> Fix Issues' Severities Hierarchy

- build.gradle
- src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
- src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
> Support Download the AnalyzerManager

- src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
- src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
> Add the Go version as a node in the Go dependencies tree

- src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
- src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
> Cleanup and Re-arrange Errors handling 

- src/main/java/com/jfrog/ide/common/nodes/VulnerabilityNode.java
- src/main/java/com/jfrog/ide/common/nodes/subentities/ApplicableInfo.java
> Fix missing data in applicability cached objects

- src/main/java/com/jfrog/ide/common/nodes/subentities/ApplicableInfo.java
- src/main/java/com/jfrog/ide/common/nodes/subentities/Evidence.java
> ApplicableInfo - add new Evidence class

- release/pipelines.release.yml
- release/pipelines.snapshot.yml
-----
Upgraded to Java 17 in the release and snapshot pipelines.
> Update release and snapshot pipelines

- build.gradle
- src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
- src/main/java/com/jfrog/ide/common/utils/Utils.java
> Adds createSSLContext Utility

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
- src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
- src/main/java/com/jfrog/ide/common/utils/Utils.java
- src/main/java/com/jfrog/ide/common/utils/XrayConnectionUtils.java
- src/test/java/com/jfrog/ide/common/utils/ConsolidatePathsTest.java
- src/test/java/com/jfrog/ide/common/utils/UtilsTest.java
-----
Required for https://github.com/jfrog/jfrog-idea-plugin/pull/359
Adaptations needed for the new SSO login feature.
> Support login by Web

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
-----
Ignore false secret issues.
> Ignore false secret issues

- build.gradle
> Update build info version to 2.41.6

- src/main/java/com/jfrog/ide/common/nodes/SastIssueNode.java
- src/main/java/com/jfrog/ide/common/nodes/subentities/SourceCodeScanType.java
> Add Support to the New Scanners Config

- src/main/java/com/jfrog/ide/common/ci/CiManagerBase.java
- src/main/java/com/jfrog/ide/common/nodes/subentities/ApplicableInfo.java
- src/main/java/com/jfrog/ide/common/utils/usage/EcosystemUsageReporter.java
- src/main/java/com/jfrog/ide/common/utils/usage/UsageReport.java
> Adds new EcosystemUsageReporter Utility

- src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
-----
Added a method for merging file nodes.
> Merge file nodes

- src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
- src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTree.java
- src/main/java/com/jfrog/ide/common/yarn/YarnTreeBuilder.java
-----
Change impact tree size limit to 20.
Some minor changes.
> Change impact tree size limit

- build.gradle
- release/pipelines.release.yml
- release/pipelines.snapshot.yml
> Release automation - temporary remove resolution repo

- release/pipelines.release.yml
-----
comment audit on release because of a bug that prevents release.
will be uncommented after release.
> Temporary remove audit for release

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
- src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
> Added cli add config functionality 

- src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
- src/main/java/com/jfrog/ide/common/parse/SarifParser.java
- src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
> Updated the sarif parser and the version cli func use
