jfrog/ide-plugins-common

src/main/java/com/jfrog/ide/common/persistency/ScanCache.java

**The issue:**
In npm projects, the project name is the project full path.
When the scan cache tries to resolve the path to the project path, it fails and returns the path to the package.json directory. This instead of returning a path to `USER_HOME/.jfrog-idea-plugin/cache/projectName_XrayScanCache.json`. The results are: XrayScanCache.json files in the workspace.
**Solution:** 
Base64 encoding of project name.

Bugfix - in npm projects, XrayScanCache.json files are created in workspace

---

build.gradle
src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
src/test/java/com/jfrog/ide/common/npm/NpmTreeBuilderTest.java
src/test/resources/npm/devAndProd/package.json

Allow npm dependency scope to have both "Production" and "Development" scopes.
One common scenario may be as the following 2 conditions exist:
1. package.json:
```json
{
"dependencies": {
"frogDep" : "1"
},
"devDependencies": {
"devDep": "1"
}
}
```
2. "frogDep:1" is also a dependency of "devDep:1" (devDep:1 -> frogDep:1). 
"frogDep:1" should have both "Production" and "Development" scopes.

Allow npm dependency to have both prod and dev scopes

---

src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java

Resolve stack overflow in Go projects that have loops in the dependency tree.
To reproduce:
Scan the following project: https://github.com/gogatekeeper/gatekeeper
The results:
> java.lang.StackOverflowError
at java.base/java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:42)
at java.base/java.util.regex.PatternSyntaxException.<init>(PatternSyntaxException.java:59)
at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
at java.base/java.lang.String.split(String.java:2317)
at java.base/java.lang.String.split(String.java:2364)
at com.jfrog.ide.common.go.GoTreeBuilder.populateDependenciesTree(GoTreeBuilder.java:97)
at …

Add loop detection mechanism in Go

---

src/main/java/com/jfrog/ide/common/ci/Utils.java
src/test/java/com/jfrog/ide/common/ci/UtilsTests.java

Encode build name patterns to support slash in the build name. Encode `%` to `?` to bypass an issue in Artifactory.
Examples:
* `buildName` -> `buildName`
* `*` -> `*`
* `build/with/slash` -> `build?2Fwith?2Fslash`

Bugfix - build patterns with slash doesn't encoded correctly

---

build.gradle
src/main/java/com/jfrog/ide/common/ci/BuildArtifactsDownloader.java
src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java

-----
Fix an issue found by @TamirHadad's - if name or version are missing in the package.json, an NPE is thrown.
This PR make the following changes:
1. Update build info to the latest version to reflect the latest changes, and include https://github.com/jfrog/build-info/pull/546 
2. When the name node is missing in package.json, show the project name as the root node of the dependency tree.

Bugfix - npm without version throws NPE

---

src/main/java/com/jfrog/ide/common/go/GoScanWorkspaceCreator.java
src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
src/test/resources/go/project1/testdata/go.mod
src/test/resources/go/project1/testdata/main.go

-----
Allow GoScanWorkspaceCreator to exclude paths. This is necessary to exclude unused test projects (i.e. files under testdata) from the Go scanner.

Allow excluding paths in GoScanWorkspaceCreator

---

src/main/java/com/jfrog/ide/common/scan/ComponentSummaryScanLogic.java
src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
src/test/java/com/jfrog/ide/common/scan/GraphScanLogicTest.java

-----
Instead of building a transitive scan tree, build a flat one.
The main reason for that change is Xray `graph/scan` API skips subtrees without versions.
This way we ensure that Xray will get only real dependencies, not modules, and hopefully gain a performance improvement.

GraphScan - Send to Xray a flat tree with dependencies only

---

src/main/java/com/jfrog/ide/common/persistency/ScanCache.java

-----
In some cases, the summary was missing while resolving the information from Xray. In this case, we have a severity and component ID, which are enough to let the user know that a component is vulnerable.

Support vulnerabilities and violations without summary

---

src/main/java/com/jfrog/ide/common/ci/BuildDependencyTree.java
src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java
src/main/java/com/jfrog/ide/common/persistency/XrayScanCacheMap.java
src/main/java/com/jfrog/ide/common/utils/Utils.java
src/test/java/com/jfrog/ide/common/filter/Utils.java
src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java

-----
Store CVEs in cache and increase cache version from 0 to 1, to make sure the cache will be initialized.

Store CVEs in cache

---

build.gradle
src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java

-----
Depends on:
* https://github.com/jfrog/build-info/pull/577
In some cases we see that running `go list` on some Go packages may fail. We should allow ignoring the errors in such cases and build the Go dependency tree, even if partial.

Allow building Go dependency tree with errors

---

build.gradle
src/main/java/com/jfrog/ide/common/ci/BuildDependencyTree.java
src/main/java/com/jfrog/ide/common/ci/Utils.java
src/main/java/com/jfrog/ide/common/exporter/Exporter.java
src/main/java/com/jfrog/ide/common/exporter/csv/CsvExporter.java
src/main/java/com/jfrog/ide/common/exporter/csv/CsvViolatedViolatedLicenseRow.java
src/main/java/com/jfrog/ide/common/exporter/csv/CsvVulnerabilityRow.java
src/main/java/com/jfrog/ide/common/exporter/exportable/ExportableComponent.java
src/main/java/com/jfrog/ide/common/exporter/exportable/ExportableViolatedLicense.java
src/main/java/com/jfrog/ide/common/exporter/exportable/ExportableVulnerability.java
src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java
src/main/java/com/jfrog/ide/common/utils/Utils.java
src/test/java/com/jfrog/ide/common/exporter/ExporterTest.java
src/test/java/com/jfrog/ide/common/filter/Utils.java
src/test/java/com/jfrog/ide/common/scan/ScanLogicTest.java
src/test/resources/exporter/issues.csv
src/test/resources/exporter/violatedLicenses.csv

-----
Depends on https://github.com/jfrog/build-info/pull/611 & https://github.com/jfrog/xray-client-java/pull/31.
* Add CSV exporter
* Store CVEs (plural), references, and ignore URL in the cache.

Add exporter, support ignore URL and vuln references

---

.github/workflows/test.yml
src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
src/test/java/com/jfrog/ide/common/npm/NpmTreeBuilderTest.java

-----
Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/192
npm >= 7 allows running ls with `--package-lock-only` flag:
> If set to true, the current operation will only use the package-lock.json, ignoring node_modules.
https://docs.npmjs.com/cli/v7/commands/npm-ls#package-lock-only
Generally, in npm, unknown flags are skipped. Therefore we can safely use this flag on npm 6, without doing any harm.

Allow scanning npm projects without node_modules

---

src/main/java/com/jfrog/ide/common/utils/PackageFileFinder.java
src/test/java/com/jfrog/ide/common/utils/PackageFileFinderTest.java
src/test/resources/packageFinder/go/go.mod
src/test/resources/packageFinder/gradle/api/build.gradle
src/test/resources/packageFinder/gradle/build.gradle
src/test/resources/packageFinder/gradle/services/webservice/build.gradle
src/test/resources/packageFinder/npm/package.json

-----
Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/198 & https://github.com/jfrog/jfrog-idea-plugin/issues/108
* It is not uncommon that users name their project `*test*`. By default, "test" is excluded from scanning. To resolve this issue, we should not exclude the base project directory.
* Improve exclusion message:
* Before:
* After:
* Add tests for PackageFileFinder.

Root project should not be excluded from scanning

---

src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java

-----
Fix the following exception:
> com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: com.jfrog.ide.common.persistency.XrayScanCacheMap["artifactsMap"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)
at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:778)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSe …

Fix ConcurrentModificationException in cache

---

src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java

when i use this artifact and build-info-extractor-2.35.0, ScanCacheMap.readCommonCache() will occur error, but i don't know what exception. Later, although I learned that it was a build-info-extractor version problem, I thought that this exception information should not be lost, but should be recorded.

when readCommonCache occur error, log exception message

---

src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java

Fix typos in the missing CLI config message

---

build.gradle
src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java

-----
Depends on: https://github.com/jfrog/build-info/pull/689
* Allow providing the dontBuildVcs flag, which can be used to skip VCS stamping to bypass the following error:
> IOException: error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping.
* Remove code duplication in Go tree building

Skip VCS stamping in Go

---

src/main/java/com/jfrog/ide/common/persistency/XrayScanCache.java
src/main/java/com/jfrog/ide/common/scan/ComponentSummaryScanLogic.java
src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
src/main/java/com/jfrog/ide/common/scan/ScanLogic.java
src/main/java/com/jfrog/ide/common/scan/ScanManagerBase.java
src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java
src/test/java/com/jfrog/ide/common/scan/GraphScanLogicTest.java
src/test/java/com/jfrog/ide/common/scan/ScanLogicTest.java

-----
Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/248
When changing watches, the cache does not get updated.
This PR changes the way we initialize the scan cache in case of a full scan, by avoiding reading the cache from the file system.

V1: Skip loading cache from file system in full scan mode

---

src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
src/main/java/com/jfrog/ide/common/nodes/DescriptorFileTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/IssueNode.java
src/main/java/com/jfrog/ide/common/nodes/LicenseViolationNode.java
src/main/java/com/jfrog/ide/common/nodes/SortableChildrenTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/VulnerabilityNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/License.java
src/main/java/com/jfrog/ide/common/nodes/subentities/ResearchInfo.java
src/main/java/com/jfrog/ide/common/nodes/subentities/SeverityReason.java
src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
src/main/java/com/jfrog/ide/common/persistency/ScanCacheObject.java
src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java

-----
Save last scan results in cache and show them on plugin startup.

Cache last scan results

---

build.gradle
src/main/java/com/jfrog/ide/common/ci/XrayBuildDetailsDownloader.java
src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/IssueNode.java
src/main/java/com/jfrog/ide/common/nodes/LicenseViolationNode.java
src/main/java/com/jfrog/ide/common/nodes/SortableChildrenTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/VulnerabilityNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/Cve.java
src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/License.java
src/main/java/com/jfrog/ide/common/nodes/subentities/ResearchInfo.java
src/main/java/com/jfrog/ide/common/nodes/subentities/SeverityReason.java

-----
Private and protected fields can't be read by ObjectMapper in newer versions of Java by default, so I handled this issue with some annotations, getters and setters.

Fix writing private and protected fields to cache

---

src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java

-----
Use an ArrayList in the watchNames field, as singleton lists and unmodifiable lists cannot be read from the cache.

Fix unreadable cache field

---

build.gradle
settings.gradle
src/main/java/com/jfrog/ide/common/deptree/DepTree.java
src/main/java/com/jfrog/ide/common/deptree/DepTreeNode.java
src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
src/main/java/com/jfrog/ide/common/gradle/GradleTreeBuilder.java
src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTreeNode.java
src/main/java/com/jfrog/ide/common/npm/NpmTreeBuilder.java
src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
src/main/java/com/jfrog/ide/common/scan/ScanLogic.java
src/main/java/com/jfrog/ide/common/yarn/YarnTreeBuilder.java
src/test/java/com/jfrog/ide/common/TestUtils.java
src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
src/test/java/com/jfrog/ide/common/gradle/GradleTreeBuilderTest.java
src/test/java/com/jfrog/ide/common/npm/NpmTreeBuilderTest.java
src/test/java/com/jfrog/ide/common/yarn/YarnTreeBuilderTest.java

-----
A new structure for the dependency trees: created a new class for dependency trees (DepTree) that has a flat tree structure to save memory.
Depends on https://github.com/jfrog/gradle-dep-tree/pull/14

Flat dependency trees

---

src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTree.java
src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
src/main/java/com/jfrog/ide/common/persistency/ScanCacheObject.java

-----
Created the ImpactTree class, that contains the impact tree itself and metadata about it.

Created ImpactTree class

---

src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
src/main/java/com/jfrog/ide/common/nodes/FileIssueNode.java
src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
src/main/java/com/jfrog/ide/common/nodes/subentities/Severity.java
src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java

-----
Fix duplications of VulnerabilityNodes in the cache, that caused errors while trying to read it.
Usually, a VulnerabilityNode is written to the cache file once: as a child of a DescriptorFileTreeNode.
If there's an ApplicableIssueNode pointing to it, then this ApplicableIssueNode contains a field with the VulnerabilityNode's UUID.
But sometimes, if the ApplicableIssueNode pointing to this VulnerabilityNode has been written before the VulnerabilityNode, then the VulnerabilityNode is written inside the ApplicableIssueNode (instead of just its UUID), and later when the DescriptorFileTreeNode (that contains this VulnerabilityNode) is written, then the VulnerabilityNode is written again.
Both times the VulnerabilityNode is written with the same UUID (because it's the same object), so …

Fix duplications in results cache

---

src/main/resources/gradle-dep-tree.gradle

-----
Avoid adding unnecessary libraries to the classpath in the init.gradle file we use for executing gradle-dep-tree.
This caused projects using Gradle <7.6 to fail, because some of these unnecessary libraries were using JDK >=14, which is not supported by it.

Fix errors when scanning projects using Gradle <7.6

---

src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
src/test/resources/go/project5/go.mod
src/test/resources/go/project5/main.go
src/test/resources/go/project6/go.mod

-----
In the case of scanning a Go module with no packages (no source code), the `go list` command returns an empty result with a warning that no packages are found. It caused the building of a dependency tree that contains a root ID, but no nodes at all, and throwing a NullPointerException later in the process. From now on, in this case, a clear error will be thrown.

Fix NullPointerException when scanning Go modules with no packages

---

src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
src/main/java/com/jfrog/ide/common/configuration/ServerConfig.java

-----
Added a custom resources repository option in the plugin's configuration.

Support for downloading scan resources from an external repository

---

src/main/java/com/jfrog/ide/common/utils/PackageFileFinder.java

-----
Due to the jfrog/jfrog-idea-plugin#435 pull request, we've already executed a `consolidatePaths` call before invoking PackageFileFinder at https://github.com/jfrog/jfrog-idea-plugin/pull/435/files#diff-2a45496f51bd41dcf256fb1bbc43f1bdc5940fd98e7c3a44f3f03209c69068aeR37. 
To eliminate redundant function calls, we've removed the `consolidatePaths` call from `PackageFileFinder`.

Remove consolidatePaths from PackageFileFinder

---

src/main/java/com/jfrog/ide/common/nodes/SastIssueNode.java

-----
Addressed an issue where IDEA navigation tab displayed empty nodes for identical SAST nodes with different codeFlows. The fix ensures that the same SAST issue now appears several times as the correct number of codeFlows, each having a distinct trace.

Fixed comparison between SastIssueNodes

---

build.gradle

-----
Update build-info version to 2.41.9, addressing a Windows issue where running Go commands could fail if the executable was located in a path with spaces.

Updated build-info version

---

build.gradle

-----
Update build-info version to 2.41.13
Updating build-info version to apply the fix for this issue: https://github.com/jfrog/build-info/pull/777

Fix running executables with spaces in their paths in Windows

---

src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java

-----
- Added support for configuring environment variables for each command executed by the JfrogCliDriver.

Add support for configuring environment variables in JfrogCliDriver

---

src/main/java/com/jfrog/ide/common/nodes/FileIssueNode.java

-----
- Implemented the toString() methos in FileIssueNode so it will return the title field (needed for Eclipse plugin TreeView presentation in the UI).

Add support for presenting FileIssueNode title by calling toString method

---

src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java

-----
- Fixed a bug of logging the config command with credentials.
- Return the value of ResultCommand when calling addCliServerConfig.

Bug fix in config command - logging credentials

---

src/main/java/com/jfrog/ide/common/nodes/ScaIssueNode.java
src/main/java/com/jfrog/ide/common/parse/Applicability.java
src/main/java/com/jfrog/ide/common/parse/SarifParser.java

-----
- Added missing info for presenting SCA issues - component name and version.
- Use the help field instead of full description when parsing SCA results.
- Changed Applicability names to be more readable for usage in IDEs UI.

Add Info to SCA Issue Node and Improve Applicability Enum String Value

---

src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
src/main/java/com/jfrog/ide/common/utils/Utils.java
src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java

-----
- Resolved an issue where the CLI download process did not verify the existence of the CLI executable in the destination folder. As a result, the version check would depend on the CLI version installed on the machine.
- Updated the download implementation to utilize URI, eliminating the need for server configuration.
- Fixed issue with MacOS architecture identification to ensure the correct CLI version is downloaded.

Fix bug when downloading CLI

---

src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java

-----
- Added the environment variable `JFROG_CLI_AVOID_NEW_VERSION_WARNING=true`  for ignoring the version warning in cli logs.

Add environment variable to the cliDriver for ignoring version warning in cli logs

---

src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactPath.java
src/main/java/com/jfrog/ide/common/parse/Applicability.java
src/main/java/com/jfrog/ide/common/webview/ApplicableDetails.java
src/main/java/com/jfrog/ide/common/webview/Cve.java
src/main/java/com/jfrog/ide/common/webview/DependencyPage.java
src/main/java/com/jfrog/ide/common/webview/Evidence.java
src/main/java/com/jfrog/ide/common/webview/ExtendedInformation.java
src/main/java/com/jfrog/ide/common/webview/Finding.java
src/main/java/com/jfrog/ide/common/webview/ImpactGraph.java
src/main/java/com/jfrog/ide/common/webview/ImpactGraphNode.java
src/main/java/com/jfrog/ide/common/webview/IssuePage.java
src/main/java/com/jfrog/ide/common/webview/JfrogResearchSeverityReason.java
src/main/java/com/jfrog/ide/common/webview/License.java
src/main/java/com/jfrog/ide/common/webview/Location.java
src/main/java/com/jfrog/ide/common/webview/Reference.java
src/main/java/com/jfrog/ide/common/webview/SastIssuePage.java
src/main/java/com/jfrog/ide/common/webview/events/Event.java
src/main/java/com/jfrog/ide/common/webview/events/IdeEvent.java
src/main/java/com/jfrog/ide/common/webview/events/WebviewEvent.java

-----
- Added common objects used by IDEA and Eclipse plugins for WebView integration and data exchange.
- Added a conversion method from Applicability to webview icon names to ensure compliance between WebView and the data in the ScaIssueNode.

Added Common Objects for WebView Integration

---

build.gradle

-----
- Upgrade project dependencies for resolving vulnerability issues: 
opencsv -> 5.11.1
commons-io -> 2.20.0

Upgrade dependencies to fix SCA vulnerability issues
